# Generated by Django 3.0.8 on 2021-08-22 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bran_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('clg_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=20)),
                ('clg_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.College')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coll_fee', models.IntegerField()),
                ('exam_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('First class', 'Grade A'), ('second class', 'Grade B2'), ('Third class', 'Grade C1'), ('fourth class', 'Grade C2'), ('Destiniction', 'Grade D1')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20)),
                ('bran_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Branch')),
                ('clg_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.College')),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Depart')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Fee')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Results')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Subject')),
                ('time_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.TimeTable')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('clg_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.College')),
                ('staff_salary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.Salary')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lect_name', models.CharField(max_length=20)),
                ('bran_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Branch')),
                ('clg_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.College')),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Depart')),
                ('lect_sal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Salary')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Subject')),
                ('time_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.TimeTable')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='clg_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.College'),
        ),
        migrations.AddField(
            model_name='branch',
            name='dep_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Depart'),
        ),
    ]
