# Generated by Django 3.0.8 on 2021-09-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='depart',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
