# Generated by Django 3.0.8 on 2021-09-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20210916_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bran_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Branch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='clg_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.College'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dep_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Depart'),
        ),
        migrations.AlterField(
            model_name='student',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Results'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='time_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.TimeTable'),
        ),
    ]
