# Generated by Django 3.0.8 on 2021-08-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='dep',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='dep',
            field=models.ManyToManyField(to='app.Dept'),
        ),
    ]
