# Generated by Django 3.0.8 on 2021-08-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=30, unique=True)),
                ('pno', models.IntegerField(blank=True, max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField()),
            ],
        ),
    ]
