# Generated by Django 3.0.8 on 2021-08-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pno',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
